export { default as Header } from './header/Header'
export { default as Footer } from './footer/Footer'
export { default as LazyLoadImage } from './lazy-load-image/LazyLoadImage'
export { default as ContextWrapper } from './content-wrapper/ContextWrapper'
export { default as SwitchTabs } from './switch-tabs/SwitchTabs'
